Repository DeveloperAcademy-POSTECH/2025-C3-A2-YAP, pull requests merged in 2025-06, with the labels that each got.

#16 색상, 아이콘, Cta버튼 추가
  YAP/YAP/Resource/Assets.xcassets/AlertIcon.imageset/AlertIcon.png
  YAP/YAP/Resource/Assets.xcassets/AlertIcon.imageset/Contents.json
  YAP/YAP/Resource/Assets.xcassets/AlertIcon.imageset/alertIcon2x.png
  YAP/YAP/Resource/Assets.xcassets/AlertIcon.imageset/alertIcon3x.png
  YAP/YAP/Resource/Assets.xcassets/background.colorset/Contents.json
  YAP/YAP/Resource/Assets.xcassets/celebrate.imageset/Contents.json
  YAP/YAP/Resource/Assets.xcassets/celebrate.imageset/celebrate2x 1.png
  YAP/YAP/Resource/Assets.xcassets/celebrate.imageset/celebrate2x.png
  YAP/YAP/Resource/Assets.xcassets/celebrate.imageset/celebrate3x.png
  YAP/YAP/Resource/Assets.xcassets/dark.colorset/Contents.json
  YAP/YAP/Resource/Assets.xcassets/darkActive.colorset/Contents.json
  YAP/YAP/Resource/Assets.xcassets/darkHover.colorset/Contents.json
  YAP/YAP/Resource/Assets.xcassets/darker.colorset/Contents.json
  YAP/YAP/Resource/Assets.xcassets/divider.colorset/Contents.json
  YAP/YAP/Resource/Assets.xcassets/gradient.colorset/Contents.json
  YAP/YAP/Resource/Assets.xcassets/healthMan.imageset/Contents.json
  YAP/YAP/Resource/Assets.xcassets/healthMan.imageset/healthMan.png
  YAP/YAP/Resource/Assets.xcassets/healthMan.imageset/healthMan2x.png
  YAP/YAP/Resource/Assets.xcassets/healthMan.imageset/healthMan3x.png
  YAP/YAP/Resource/Assets.xcassets/light.colorset/Contents.json
  YAP/YAP/Resource/Assets.xcassets/lightActive.colorset/Contents.json
  YAP/YAP/Resource/Assets.xcassets/lightHover.colorset/Contents.json
  YAP/YAP/Resource/Assets.xcassets/main.colorset/Contents.json
  YAP/YAP/Resource/Assets.xcassets/placeholder.colorset/Contents.json
  YAP/YAP/Resource/Assets.xcassets/primaryActive.colorset/Contents.json
  YAP/YAP/Resource/Assets.xcassets/primaryHover.colorset/Contents.json
  YAP/YAP/Resource/Assets.xcassets/subBackground.colorset/Contents.json
  YAP/YAP/Resource/Assets.xcassets/subTextColor.colorset/Contents.json
  YAP/YAP/Resource/Assets.xcassets/textColor.colorset/Contents.json
  YAP/YAP/Resource/DesignSystem/ButtonStyle/CtaButton.swift
  YAP/YAP/Resource/DesignSystem/ButtonStyle/CtaButtonLabel.swift
  YAP/YAP/Resource/DesignSystem/Color/LinearGradient+Ex.swift
  YAP/YAP/Resource/DesignSystem/Font/Pretendard-Bold.otf
  YAP/YAP/Resource/DesignSystem/Font/Pretendard-Light.otf
  YAP/YAP/Resource/DesignSystem/Font/Pretendard-Medium.otf
  YAP/YAP/Resource/DesignSystem/Font/Pretendard-Regular.otf
  YAP/YAP/Resource/DesignSystem/Font/Pretendard-SemiBold.otf
  YAP/YAP/Resource/DesignSystem/Spacing/Spacing.swift
Labels: ⚙️ Setting, 🫣 Hong

#20 [FEAT] 다크모드 비활성화, 팀 협업 위한 Bundle ID 수정
  YAP/YAP.xcodeproj/project.pbxproj
  YAP/YAP/Develop.xcconfig
Labels: ⚙️ Setting, ☝🏻 iL

#29 Feat: foodSearch witch ML
  YAP/YAP/Info.plist
  YAP/YAP/Resource/Assets.xcassets/mainWhite.colorset/Contents.json
  YAP/YAP/Resource/DesignSystem/Image/Image.swift
  YAP/YAP/Source/Data/Enums/NutritionUnit.swift
  YAP/YAP/Source/Data/Models/150classesFood.mlmodel
  YAP/YAP/Source/Data/Models/NutritionModel.swift
  YAP/YAP/Source/Feature/Camera/CameraView.swift
  YAP/YAP/Source/Feature/FoodSearch/Cart/CartItemRow.swift
  YAP/YAP/Source/Feature/FoodSearch/Cart/CartManager.swift
  YAP/YAP/Source/Feature/FoodSearch/Cart/CartView.swift
  YAP/YAP/Source/Feature/FoodSearch/Cart/NutritionCircle.swift
  YAP/YAP/Source/Feature/FoodSearch/Modal/FoodModalView.swift
  YAP/YAP/Source/Feature/FoodSearch/Modal/ModalCircle.swift
  YAP/YAP/Source/Feature/FoodSearch/Search/FoodItemRow.swift
  YAP/YAP/Source/Feature/FoodSearch/Search/FoodSearchView.swift
  YAP/YAP/Source/Feature/FoodSearch/Service/Format.swift
  YAP/YAP/Source/Feature/FoodSearch/Service/NutritionService.swift
  YAP/YAP/Source/Feature/ImagePredictor/FoodCameraCapture.swift
  YAP/YAP/Source/Feature/ImagePredictor/FoodCameraView.swift
  YAP/YAP/Source/Feature/ImagePredictor/ImagePredictionHandler.swift
  YAP/YAP/Source/Feature/ImagePredictor/ImagePredictor.swift
  YAP/YAP/Source/Utilities/Error/MLError.swift
  YAP/YAP/Source/Utilities/Extensions/CGImagePropertyOrientation+Ex.swift
  YAP/YAP/Source/Utilities/Extensions/String+Ex.swift
Labels: ✨ Feat, 🫣 Hong

#43 [FEAT] 메인화면 UI 오류 수정
  YAP/YAP/Source/App/ContentView.swift
  YAP/YAP/Source/App/YAPApp.swift
  YAP/YAP/Source/Feature/MainUI/CalorieSummaryView.swift
  YAP/YAP/Source/Feature/MainUI/CustomCalendarView.swift
  YAP/YAP/Source/Feature/MainUI/MainUIView.swift
  YAP/YAP/Source/Feature/MainUI/MealEntryView.swift
  YAP/YAP/Source/Feature/MainUI/NutrientSectionView.swift
  YAP/YAP/Source/Feature/Onboarding/OnboardingResultView.swift
Labels: 🐛 Fix, 🕰️ Gyeong

#49 [FIX] 메인화면 재수정
  YAP/YAP.xcodeproj/project.pbxproj
  YAP/YAP/Info.plist
  YAP/YAP/Source/Feature/MainUI/CalendarScrollView.swift
  YAP/YAP/Source/Feature/MainUI/CalorieSummaryView.swift
  YAP/YAP/Source/Feature/MainUI/DateSelectionView.swift
  YAP/YAP/Source/Feature/MainUI/MealEntryView.swift
  YAP/YAP/Source/Feature/MainUI/NutrientSectionView.swift
Labels: ✨ Feat, 🐛 Fix, 🕰️ Gyeong

#47 [FIX] 더미데이터 수정 및 로직추가
  YAP/YAP/Source/Feature/FoodSearch/Cart/Adjustment/CalorieAdjustmentView.swift
  YAP/YAP/Source/Feature/FoodSearch/Cart/CartView/CartView.swift
  YAP/YAP/Source/Feature/FoodSearch/Cart/CartView/NutritionCircle.swift
  YAP/YAP/Source/Feature/FoodSearch/Cart/Manager/CartDataManager.swift
  YAP/YAP/Source/Feature/FoodSearch/Cart/Manager/CartManager.swift
Labels: ✨ Feat, 🐛 Fix, ⚡️ Kadan

#56 [FIX] 수정
  YAP/YAP/Source/Feature/FoodSearch/Cart/Adjustment/CalorieAdjustmentView.swift
  YAP/YAP/Source/Feature/FoodSearch/Cart/Adjustment/ExerciseView.swift
  YAP/YAP/Source/Feature/FoodSearch/Cart/CartView/CartView.swift
  YAP/YAP/Source/Feature/FoodSearch/Cart/CartView/NutritionCircle.swift
  YAP/YAP/Source/Feature/FoodSearch/Search/FoodSearchView.swift
  YAP/YAP/Source/Feature/FoodSearch/Service/Notification.swift
Labels: 🐛 Fix, ⚡️ Kadan

#57 [#33] 인바디 결과지 분석 구현
  YAP/YAP.xcodeproj/project.pbxproj
  YAP/YAP.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  YAP/YAP/Source/App/YAPApp.swift
  YAP/YAP/Source/Data/Models/OnboardingModel.swift
  YAP/YAP/Source/Feature/Onboarding/Components/CameraPreviewView.swift
  YAP/YAP/Source/Feature/Onboarding/GuideLineView.swift
  YAP/YAP/Source/Feature/Onboarding/OnboardingInbodyOcrView.swift
  YAP/YAP/Source/Feature/Onboarding/OnboardingMainView.swift
  YAP/YAP/Source/Utilities/Support/AppCheckManager.swift
  YAP/YAP/Source/Utilities/Support/CameraManager.swift
  YAP/YAP/Source/Utilities/Support/FireBaseManager.swift
Labels: ✨ Feat, ☝🏻 iL, 🫣 Hong

#59 [FIX] 각종 수정
  YAP/YAP/Source/Feature/FoodSearch/Cart/Adjustment/CalorieAdjustmentView.swift
  YAP/YAP/Source/Feature/FoodSearch/Cart/Adjustment/DietView.swift
  YAP/YAP/Source/Feature/FoodSearch/Cart/Adjustment/ExerciseView.swift
  YAP/YAP/Source/Feature/FoodSearch/Cart/CartView/CartItemRow.swift
  YAP/YAP/Source/Feature/FoodSearch/Cart/CartView/CartView.swift
  YAP/YAP/Source/Feature/FoodSearch/Cart/CartView/NutritionCircle.swift
  YAP/YAP/Source/Feature/FoodSearch/Search/FoodSearchView.swift
Labels: 🐛 Fix, ⚡️ Kadan
